---
- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: docker status
      service:
        name: docker
        state: started
        enabled: yes
        tags: 
        - docker

- name: Verify NFS Shared Volumes on Hosts
  hosts: nfs
  tasks:
    - name: Test NFS Exports 
      shell: exportfs