---
- hosts: localhost
  tasks:
  - name: ansible-register-variable-basic-example
    shell: 'hostname | cut -d"." -f2'
    args:
      chdir: "/"
    register: returned_guid
  - set_fact:
      guid: "{{ returned_guid }}"     

- hosts: nodes
  become: true
  vars:
    guid: "{{ hostvars['localhost']['guid'].stdout }}"
  roles:
    - systems
    - docker

- hosts: nfs
  become: true
  roles:
    - { role: nfs,
        tags: ['export_nfs'] }