---
- hosts: localhost
  vars:
  roles:
    - bastion

- hosts: localhost
  tasks:
  - name: refresh-inventory
    meta: refresh_inventory

- hosts: nodes
  become: true
  vars:
    guid: "{{ hostvars['localhost']['guid'].stdout }}"
  roles:
    - systems
    - docker

- hosts: nfs
  become: true
  roles:
    - { role: nfs,
        tags: ['export_nfs'] }

#- name: Execute the openshift-ansible prerequisites
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

#- name: Execute the openshift-ansible Deployer
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: collect-kube-creds-from-master
  hosts: masters[0]
  tasks:
    - name: retrieve-the-kube-directory-from-a-master-to-bastion
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

- name: validate-kube-config-auth
  hosts: localhost
  tags: test-auth
  tasks:
    - name: check-system-admin
      shell: oc whoami | grep system:admin
      register: whoami
#    - debug:
#        var: whoami
    - name: echo-result
      shell: 'echo Congratulations you have become the "{{ whoami.stdout }}"'
      register: out
      when: whoami.stdout.find('admin') != -1
    - debug: 
        msg: "{{ out.stdout }}"
    - fail:
        msg: "you are not system:admin"
      when: whoami.stdout.find('system') = -1

- hosts: nfs
  become: true
  roles:
    - { role: nfs,
        tags: ['create_pvs'] }

- name: create-25-5GB-pvs-definition-files
  hosts: localhost
  tasks:
    - script: scripts/pvs_5Gsize.sh
      args:
        creates: /root/pvs/pv1

#- name: Create 25 definitions files for PVs 10G size

#- name: Create all PVs from definitions files        