---
apiVersion: v1
groupNames:
- system:serviceaccounts:cicd-prod
- system:serviceaccounts:cicd-test
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:image-puller
  namespace: cicd-dev
roleRef:
  name: system:image-puller
subjects:
- kind: SystemGroup
  name: system:serviceaccounts:cicd-prod
- kind: SystemGroup
  name: system:serviceaccounts:cicd-test
kind: List
metadata: {}
