---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rolebinding
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: cicd
  userNames:
  - system:serviceaccount:cicd:jenkins